---
- name: check connectivity
  ping:
    data: alive

- name: Fine-tune the kernel module to optimize ceph nodes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    sysctl_file: "/etc/sysctl.conf"
    state: present
    reload: true
  with_items:
    - { name: "vm.overcommit_memory", value: '1' }
    - { name: "net.ipv4.ip_forward", value: '1' }
    - { name: "net.core.somaxconn", value: '4096' }
    - { name: "vm.max_map_count", value: '262144' }
    - { name: "vm.dirty_ratio", value: '10' }
    - { name: "vm.dirty_background_ratio", value: '10' }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: '4096' }
    - { name: "net.ipv4.tcp_tw_reuse", value: '1' }
    - { name: "net.ipv4.tcp_fin_timeout", value: '20' }
    - { name: "net.ipv4.ip_local_port_range", value: '30000 65535' }
    - { name: "net.core.rmem_max", value: '33554432' }
    - { name: "net.core.wmem_max", value: '33554432' }
    - { name: "net.ipv4.tcp_rmem", value: '4096 87380 33554432' }
    - { name: "net.ipv4.tcp_wmem", value: '4096 16384 33554432' }
    - { name: "net.core.netdev_max_backlog", value: '7000' }
    - { name: "net.ipv4.tcp_max_tw_buckets", value: '300000' }
    - { name: "net.ipv4.tcp_slow_start_after_idle", value: '1' }
    - { name: "net.ipv4.tcp_timestamps", value: '1' }
    - { name: "net.ipv4.tcp_window_scaling", value: '1' }
    - { name: "net.ipv4.tcp_syncookies", value: '1' }
    - { name: "net.ipv4.tcp_fastopen", value: '3' }
    - { name: "net.ipv4.tcp_keepalive_time", value: '1800' }
    - { name: "net.ipv4.tcp_keepalive_probes", value: '5' }
    - { name: "net.ipv4.tcp_congestion_control", value: "bbr"}
